### ISSUE TITLE
Plans to add this to the FreeCAD Path workbench at some point?

### ISSUE THREAD

**Issue by luzpaz** [kovacevic39/laser_post#1]
HI, just wondering if you had the intention and the ETA of adding this Laser post-processor to FreeCAD core?  

CC @sliptonic

**Comment by kovacevic39** [comment]
If there is enough interest I will do a PR, I don't have a ETA. I haven't done a lot of testing yet and would like to have some FreeCAD users with lasers try it and see what they think. I will make a post in the forum soon to see how much interest there is.

**Comment by luzpaz** [comment]
There is interest. Please tag me when you have time to make the forum post. I'll spread the word once that happens. :pray:

**Comment by luzpaz** [comment]
bump

**Comment by luzpaz** [comment]
Did you this get traction ?
